package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	"hospital-management/server/database"
	"hospital-management/server/routes"

	_ "hospital-management/server/docs" // generated by swag init

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           Hospital Management APIs
// @version         1.0
// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @schemes http https
func main() {
	// Load .env file (ignored in production where env vars are set externally)
	if err := godotenv.Load(".env.example"); err != nil {
		log.Println("⚠️  No .env file found, using system environment variables")
	}

	// Connect to database and run AutoMigrate
	database.ConnectDB()

	// Set up Gin router
	r := gin.Default()

	// CORS middleware — allows Angular dev server (localhost:4200) and production origins
	r.Use(func(c *gin.Context) {
		origin := c.GetHeader("Origin")
		allowedOrigins := map[string]bool{
			"http://localhost:4200": true,
			"http://localhost:8080": true,
		}
		if allowedOrigins[origin] {
			c.Header("Access-Control-Allow-Origin", origin)
		}
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization")
		c.Header("Access-Control-Max-Age", "86400")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}
		c.Next()
	})

	// Health check
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"message": "pong"})
	})

	// Swagger UI
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Register application routes
	routes.RegisterRoutes(r)

	// Determine port
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	fmt.Printf("🚀  Server running on http://localhost:%s\n", port)
	fmt.Printf("📖  Swagger UI  : http://localhost:%s/swagger/index.html\n", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
